name:                hs-servant-test
version:             0.1.0.0
github:              "ebrulato/hs-servant-test"
license:             MIT
author:              "Eric Brulatout"
maintainer:          "eric.brulatout@gmail.com"
copyright:           "2019 Eric Brulatout"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-servant-test#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- time
- servant-server
- warp

library:
  source-dirs: src

executables:
  hs-servant-test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-servant-test

tests:
  hs-servant-test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-servant-test
